// صفحه‌هایی که آزمون دسترس‌پذیری و چیدمان روی آن‌ها اجرا می‌شود — [نشانی، نقش]
export const PAGES = [
  ['/discover', null],
  ['/salons/view/saln-zibaii-glarh', null],
  ['/s/araishgah-parsa', null],
  ['/s/saln-zibaii-glarh', null],
  ['/s/araishgah-parsa/menu', null],
  ['/login', null],
  ['/me/login', null],
  ['/panel', 'owner'],
  ['/panel/bookings', 'owner'],
  ['/panel/bookings/new', 'owner'],
  ['/panel/customers', 'owner'],
  ['/panel/services', 'owner'],
  ['/panel/services/create', 'owner'],
  ['/panel/staff', 'owner'],
  ['/panel/staff/create', 'owner'],
  ['/panel/settings', 'owner'],
  ['/panel/reports', 'owner'],
  ['/panel/reports/monthly', 'owner'],
  ['/panel/publication', 'owner'],
  ['/panel/qr', 'owner'],
  ['/panel/sms', 'owner'],
  ['/panel', 'reception'],
  ['/panel/bookings', 'reception'],
  ['/panel', 'staff'],
  ['/platform', 'admin'],
  ['/platform/moderation', 'admin'],
  ['/platform/holidays', 'admin'],
  ['/system/updates', 'admin'],
  ['/system/design', 'admin'],
];

export const authFile = (role) => (role ? new URL(`./.auth/${role}.json`, import.meta.url).pathname : undefined);
